---
title: "RWork- sheet_Redosendo#4b"
author: "Kyle Edward B. Redosendo"
date: "2025-11-16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#1. Using the for loop, create an R script that will display a 5x5 matrix as shown inFigure 1. It must contain vector A = [1,2,3,4,5] and a 5 x 5 zero matrix.
vectorA <- 1:5
mat <- matrix(0, nrow = 5, ncol = 5)

for(i in 1:5){
for(j in 1:5){
mat[i,j] <- abs(vectorA[j] - i)
}
}
print(mat)
```

```{r}
#2. Print the string "*" using for() function. The output should be the same as shown in Figure
for(i in 1:5){
for(j in 1:i){
cat("*")
}
cat("\n")
}
```

```{r}
#3. Get an input from the user to print the Fibonacci sequence starting from the 1st input up to 500. Use repeat and break statements. Write the R Scripts and its output.
n <- 5
a <- 0
b <- 1
cat("Fibonacci numbers starting from", n, "up to 500:\n")
repeat {
fib <- a + b
if (fib > 500) break
if (fib >= n) cat(fib, " ")
a <- b
b <- fib
}
cat("\n")
```

```{r}
#4. Import the dataset as shown in Figure 1 you have created previously.
fig1 <- matrix(c(0,1,2,3,4,
1,0,1,2,3,
2,1,0,1,2,
3,2,1,0,1,
4,3,2,1,0), nrow=5, byrow=TRUE)
write.csv(fig1, "figure1.csv", row.names=FALSE)
figure1 <- read.csv("figure1.csv", header=FALSE)
print(figure1)

shoe_size <- c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 12.0, 10.5,
13.0, 11.5, 8.5, 5.0, 10.0, 6.5, 7.5, 8.5, 10.5, 10.5, 11.0, 9.0, 13.0)
height <- c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 70.0, 71.0, 72.0, 64.0, 74.5, 67.0, 71.0, 71.0,
77.0, 72.0, 59.0, 62.0, 72.0, 66.0, 64.0, 67.0, 73.0, 72.0, 69.0, 69.0, 70.0)
gender <- c("F", "F", "F", "F", "M", "F", "F", "F", "M", "F", "M", "F", "M", "M",
"M", "M", "F", "F", "M", "F", "F", "M", "M", "M", "M", "M", "M")

df <- data.frame(Shoe_size = shoe_size, Height = height, Gender = gender)
write.csv(df, "figure3.csv", row.names = FALSE)

gender_count <- table(df$Gender)
barplot(gender_count, col=c("pink","lightblue"), main="Number of Males and Females in Household Data", xlab="Gender", ylab="Number of Individuals")
legend("topright", legend=names(gender_count), fill=c("pink","lightblue"))
```

```{r}
#5. The monthly income of Dela Cruz family was spent on the following:
expenses <- c(60, 10, 5, 25)
categories <- c("Food", "Electricity", "Savings", "Miscellaneous")
percent <- round(expenses / sum(expenses) * 100)
labels <- paste(categories, percent, "%")
pie(expenses,
    labels = labels,
    col = c("orange", "yellow", "lightgreen", "skyblue"),
    main = "Monthly Income Distribution of Dela Cruz Family")
```

```{r}
#6. Use the iris dataset.
data(iris)
mean_values <- colMeans(iris[, 1:4])

species_count <- table(iris$Species)
pie(species_count, col = c("lightpink", "lightblue", "lightgreen"), main = "Species Distribution in Iris Dataset", labels = paste(names(species_count), species_count))
setosa <- subset(iris, Species == "setosa")
versicolor <- subset(iris, Species == "versicolor")
virginica <- subset(iris, Species == "virginica")

colors <- c("red", "blue", "green")
species_colors <- colors[as.numeric(iris$Species)]
plot(iris$Sepal.Length, iris$Sepal.Width, col = species_colors, pch = 19, main = "Iris Dataset", sub = "Sepal width and length", xlab = "Sepal Length", ylab = "Sepal Width")
legend("topright", legend = levels(iris$Species), col = colors, pch = 19)
```

